$(document).ready(_=>{
    $(".desktopowe").hover(
        function(){
            $(".desktopowe-menu").slideDown()
        },
        function(){
            $(".desktopowe-menu").slideUp()
        });
});